config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "links#index"

  resources :links do
    member do 
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
	belongs_to :user
end

app/models/link.rb
require 'uri'
class Link < ActiveRecord::Base
	acts_as_votable
	validates_presence_of :title
	validates_presence_of :url
	validates_format_of :url, :with => /\A(http[s]?:\/\/)?www.amazon.com\/([\w-]+\/)?(dp|gp\/product)\/(\w+)?(\w{10})(.*)\Z/ix
	belongs_to :user
	has_many :comments



	def create_referral_link
		asin = url.match(/\/(dp|gp\/product)\/([^\/]*)/)
		self.url = "http://www.amazon.com/dp/#{asin[2]}" # put referal id HERE
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :replies, :through => :links, :source => :comments
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :load_link

	def create
		@comment = @link.comments.new(comment_params)
		@comment.user = current_user
		if @comment.save
			redirect_to @link
		else
			redirect_to @link, alert: 'Unable to add comment'
		end
	end

	def destroy
		@comment = @link.comments.find(params[:id])
		@comment.destroy
		redirect_to @link, notice: 'Comment deleted'
	end

	private
		def load_link
			@link = Link.find(params[:link_id])
		end

		def comment_params
			params.require(:comment).permit(:link_id, :body, :user_id)
		end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    @link.create_referral_link

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote 
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user %>
				<%= link_to 'Destroy', link_comment_path(@link.id, comment.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazonApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-default" role="navigation">
		<div class="navbar-inner">
			<div class="container">
				<div id="logo" class="navbar-brand"><%= link_to "Site", root_path %></div>
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<% if user_signed_in? %>
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to "Submit Link", new_link_path %></li>
							<li><%= link_to "Account", edit_user_registration_path %></li>
							<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
						</ul>
					<% else %>
						<ul class="nav navbar-nav pull-right">
							<li><%= link_to "Sign Up", new_user_registration_path %></li>
							<li><%= link_to "Sign In", new_user_session_path %></li>
						</ul>
					<% end %>
				</div>
			</div>
		</div>
	</header>

	<div id="main_content" class="container">

		<div id="content" class="col-md-9 center-block">
			<%= yield %>
		</div>
	</div>



</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title, link %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.email %></small>
    </h2>

    <div class="btn-group">
    	<a class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
    	<%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
    		<span class="glyphicon glyphicon-chevron-up"></span>
    		Upvote
    		<%= link.get_upvotes.size %>
    	<% end %>
    	<%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
    		<span class="glyphicon glyphicon-chevron-down"></span>
    		Downvote
    		<%= link.get_downvotes.size %>
    	<% end %>
    </div>
  </div>
<% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="page-header">
	<h1>
		<a href="<%= @link.url %>"><%= @link.title %></a><br>
		<small>Submitted by <%= @link.user.email %></small>
	</h1>
</div>

<div class="btn-group">
	<%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
</div>

<% if @link.user == current_user %>
	<div class="btn-group">
		<%= link_to "Edit", edit_link_path(@link), class: "btn btn-default" %>
		<%= link_to "Destroy", @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>

<div class="btn-group pull-right">
	<%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
		<span class="glyphicon glyphicon-chevron-up"></span>
		Upvote
		<%= @link.get_upvotes.size %>
	<% end %>
	<%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
		<span class="glyphicon glyphicon-chevron-down"></span>
		Downvote
		<%= @link.get_downvotes.size %>
	<% end %>
</div>

<!-- REMOVE THIS IF STATEMENT -->

<h3 class="comments_title">
	<%= @link.comments.count %> Comments
</h3>


<div id="comments">
	<%= render :partial => @link.comments %>
</div>

<%= simple_form_for [@link, Comment.new] do |f| %>
	<div class="field">
		<%= f.text_area :body, class: "form-control" %>
	</div>
	<br>
	<%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>